- name: Add an Administrator
  hosts: "{{chote}}"
  become: yes
  roles:
  - AddUser

- name: SSH create key
  hosts: "{{chote}}"
  become: yes
  roles:
  - sshKeyGen

- name: install all the needed for an Developer
  hosts: "{{chote}}"
  become: yes
  roles:
  - install

- name: install and config ntp service
  hosts: "{{chote}}"
  become: yes
  roles:
  - ntp

- name: Set the Firewall (iptable)
  hosts: "{{chote}}"
  become: yes
  roles:
  - firewall

- name: Put the Nodes in the AD
  hosts: "{{chote}}"
  become: yes
  roles:
  - AD
