---
# tasks file for AddUser

- name: création of an Administrator
  user:
    name: Axel
    state: present
    shell: /bin/bash
    groups: sudo
    append: yes
    password: "{{ '@dmin-28' | password_hash('sha512') }}"
  become: yes
