---
# tasks file for AD

- name: install realm and all you need for you AD connection
  shell: 'apt-get install -y realmd sssd sssd-tools libnss-sss libpam-sss adcli samba-common-bin oddjob oddjob-mkhomedir packagekit'
  become: yes

- name: join the AD realm
  shell: 'realm join --user=Administrateur OC.Projet6.AD'
  become: yes
