---
# tasks file for firewall

- name: Reset the current iptables
  shell: 'iptables -X'
  become: yes

- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: Accept tcp INPUT on ssh
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: Accept tcp OUTPUT on ssh
  iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: Accept udp INPUT on ssh
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: 22
    jump: ACCEPT

- name: Accept udp OUTPUT on ssh
  iptables:
    chain: OUTPUT
    protocol: udp
    destination_port: 22
    jump: ACCEPT


- name: Accept INPUT icmp
  iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT

- name: Accept OUTPUT icmp
  iptables:
    chain: OUTPUT
    protocol: icmp
    jump: ACCEPT

- name: Drop default INPUT
  iptables:
    chain: INPUT
    protocol: all
    jump: DROP

- name: persistent rules
  shell: iptables-save > /etc/iptables/rules.v4
