---
# tasks file for sshKeyGen

- name: create ssh directory
  file:
    path: /home/Axel/ssh/
    state: directory
    owner: root
  become: yes

- name: create ssh_key file
  file:
    path: /home/Axel/ssh/ssh_key
    state: touch
    owner: root
    group: root
    mode: 0755
  become: yes

- name: generate SSH key
  openssh_keypair:
    path: /home/Axel/ssh/ssh_key
    type: rsa
    size: 4096
    state: present
    force: yes
  become: yes
